# Setup
title:               'Fail fast'
tagline:             'fail often, fail cheap.'
description:         'Спільнота для стартаперів. <br/> Стартап — це новий бізнес, який від початку націлений на швидкий ріст з метою захопити значну долю ринку.'
url:                 https://failfast.org.ua
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Володимир Лісівка
  email:             vlisivka@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-134312-4
